### ISSUE TITLE
Implement new water textures

### ISSUE THREAD

**Issue by nicolettehayes** [stamen/living-liquid#18]
The water is made up of 4 layers: 

- a base gradient (that determines daytime/nighttime), 
- a small scale semi-transparent pattern overlay, 
- a larger scale semi-transparent pattern overlay, and 
- a regular squiggly line pattern

Motion can be achieved by shifting the 2 middle layers and possibly keeping the top layer fixed.

Time can be conveyed by gradually lightening and darkening the base gradient.

BASE GRADIENT-DAYTIME
![screen shot 2017-02-02 at 4 53 37 pm](https://cloud.githubusercontent.com/assets/12550451/22575075/2c9c94e0-e968-11e6-8995-1e90fe2bd29c.png)
 #7fb4b2 #12839a #37707c

BASE GRADIENT-NIGHTTIME
![screen shot 2017-02-02 at 5 27 13 pm](https://cloud.githubusercontent.com/assets/12550451/22575800/e28985a2-e96c-11e6-9293-ec2afd099ba9.png)
#619092 #176c7f #2d5e69

SMALL SCALE PATTERN OVERLAY
![water-small pattern](https://cloud.githubusercontent.com/assets/12550451/22575619/96502c96-e96b-11e6-9330-bd4451e58fbd.png)

LARGER SCALE PATTERN OVERLAY
![water-larger pattern](https://cloud.githubusercontent.com/assets/12550451/22575622/9b3c81dc-e96b-11e6-9da3-076452d116cc.png)

SQUIGGLY LINES
Achieved using a "zigzag" parameter in Illustrator on a 7px line weight:
![screen shot 2017-02-02 at 4 59 39 pm](https://cloud.githubusercontent.com/assets/12550451/22575227/09bcbcb0-e969-11e6-976f-b01a1135d6e0.png)
![water-squiggles](https://cloud.githubusercontent.com/assets/12550451/22575520/d71ca408-e96a-11e6-9161-ff868fb51c1c.png)

**Comment by ericsoco** [comment]
complete as of https://github.com/stamen/living-liquid/commit/a1bc9e544b8136a298a250c8889c540c997925fe
