### ISSUE TITLE
Text-based Control Panel

### ISSUE THREAD

**Issue by nicolettehayes** [stamen/living-liquid#19]
One drawback designwise to the text-based list is that it's less flexible for different numbers of functions. The way it is currently laid out comfortably accommodates 4; it would take very different specs to accommodate 8.

![screen shot 2017-02-03 at 4 58 55 pm](https://cloud.githubusercontent.com/assets/12550451/22614500/90acc58e-ea37-11e6-9b10-349f00e80ed8.png)

Here are 4 possible function/illustration combos:
![control-panel_artboard 29](https://cloud.githubusercontent.com/assets/12550451/22614528/f6a6913a-ea37-11e6-9ec2-d84a969cfb2e.png)
![control-panel_artboard 32](https://cloud.githubusercontent.com/assets/12550451/22614530/f86e4ae4-ea37-11e6-95d5-a9a2b5f71c30.png)
![control-panel_artboard 30](https://cloud.githubusercontent.com/assets/12550451/22614532/fa65c2be-ea37-11e6-8154-c1304ebbbcd1.png)
![control-panel_artboard 31](https://cloud.githubusercontent.com/assets/12550451/22614533/fbe04330-ea37-11e6-90c2-74818224b5ac.png)

**Comment by ericsoco** [comment]
Naw, we can use this for > 4 -- just scroll the list to only show e.g. the most recent four, or the past 2 + current 1 + upcoming 1.

**Comment by nicolettehayes** [comment]
the dimensions/scale are pretty bull, but here's a start!

![control-panel_background](https://cloud.githubusercontent.com/assets/12550451/22701369/c5aa1f9c-ed5d-11e6-945b-d90866b737db.png)
<img width="4180" alt="control-panel_background 2x" src="https://cloud.githubusercontent.com/assets/12550451/22701370/c5ac8f34-ed5d-11e6-8b3a-43eb4dcd5575.png">

**Comment by ericsoco** [comment]
These two images look the same, @nicolettehayes ?

**Comment by nicolettehayes** [comment]
You've probably discovered this by now, but I just provided the png at 2 different resolutions because I was unsure which would be appropriate for 4k! Or if you wanted an svg, which github doesn't allow me to attach so it was dropped directly into slack.

**Comment by ericsoco** [comment]
Closing in favor of #25.
