### ISSUE TITLE
endzone layout

### ISSUE THREAD

**Issue by nicolettehayes** [stamen/living-liquid#23]
gotta dial this in, but it could have

- headline

- text

- clock

- o2/co2 levels

- cascade viz

<img width="1092" alt="screen shot 2017-02-16 at 3 40 38 pm" src="https://cloud.githubusercontent.com/assets/12550451/23048030/2ecfd0be-f468-11e6-8adc-29e09d867d42.png">

**Comment by ericsoco** [comment]
Closing in favor of other issues and discussion on Basecamp.
