### ISSUE TITLE
control panel design

### ISSUE THREAD

**Issue by nicolettehayes** [stamen/living-liquid#25]
getting there, but need to resolve absolute versus relative time

<img width="1057" alt="screen shot 2017-02-16 at 3 40 26 pm" src="https://cloud.githubusercontent.com/assets/12550451/23047999/fc92fd42-f467-11e6-8f45-f9c0f3346826.png">

**Comment by ericsoco** [comment]
@nicolettehayes please reassign once the design is locked.

**Comment by ericsoco** [comment]
Closing in favor of #32
