### ISSUE TITLE
revised bug design

### ISSUE THREAD

**Issue by nicolettehayes** [stamen/living-liquid#26]
<img width="779" alt="screen shot 2017-02-16 at 3 40 32 pm" src="https://cloud.githubusercontent.com/assets/12550451/23048191/2b8544d8-f469-11e6-99e0-36c79c9a7054.png">

provide assets for soco here.

**Comment by ericsoco** [comment]
@nicolettehayes please drop assets here thanky kindly!

**Comment by ericsoco** [comment]
Closing in favor of #31
