### ISSUE TITLE
Control Panel Assets

### ISSUE THREAD

**Issue by nicolettehayes** [stamen/living-liquid#32]
**Mock of everything together**

![screen shot 2017-02-27 at 11 51 32 am](https://cloud.githubusercontent.com/assets/12550451/23377017/2732f646-fce3-11e6-838d-409af8e63b5c.png)

**Assets**

Background:
![control-panel-01](https://cloud.githubusercontent.com/assets/12550451/23376961/f8ae6dd2-fce2-11e6-9237-32566f7a85a6.png)

Type: #316469 Explo Medium 30px, Explo Light Italic 24px, Explo Light 14px (18px line-spacing)
![screen shot 2017-02-27 at 11 56 02 am](https://cloud.githubusercontent.com/assets/12550451/23377174/c7ef55a2-fce3-11e6-8567-2e1da3ecc4c0.png)

Timeline:
![screen shot 2017-02-27 at 12 03 36 pm](https://cloud.githubusercontent.com/assets/12550451/23377399/c82eb0f2-fce4-11e6-9247-7de2ebf01374.png)

dimensions 365px wide 95px high, 1px line stroke, #37707c

On a 24 hour scale with day/night at 7am/7pm, each day portion is centered in different width sections:
night=6 | dawn=2 | morning=4 | afternoon=6 | dusk=2 | night=4
![screen shot 2017-02-27 at 12 13 26 pm](https://cloud.githubusercontent.com/assets/12550451/23377979/a692768e-fce6-11e6-8a65-e86a9174f07c.png)

playhead
![control-panel-playhead-day](https://cloud.githubusercontent.com/assets/12550451/23379458/db63979e-fceb-11e6-8285-05a65d0e12c7.png)
![control-panel-playhead-night](https://cloud.githubusercontent.com/assets/12550451/23379460/db74fc6e-fceb-11e6-87cb-ad50ea352769.png)

type (axis)
#316469 Explo regular 10px, lowercase, centered

type (content)
Explo medium 12px, all-caps, centered, virus #000000, Sar116 #e8b763, Prochlo #a3b841

Content blocks on timeline are #7fb4b2 at 70% opacity, multiplied.

Content block heights are 30px, widths should be determined based loosely off of the 24-hour scale. Everything should sit on a single line unless it coincides with another function, in which case it appears on the second line. Leave 2 px gap between blocks (side to side and up and down).

![screen shot 2017-02-27 at 1 02 41 pm](https://cloud.githubusercontent.com/assets/12550451/23379776/14644722-fced-11e6-9f0c-f2c6836238ab.png)

Function Illustration:
![screen shot 2017-02-27 at 1 03 23 pm](https://cloud.githubusercontent.com/assets/12550451/23379795/262fe902-fced-11e6-82ee-cd43ea0b1700.png)

box color #7fb4b2 at 70% opacity, multiplied.
box dimensions 365px x 120px
arrow 30px x 15px, right angle, 45 degrees.

text
Type: #316469 Explo Medium 16px, Explo Light 14px (18px line-spacing) 
185px x 80px, vertically centered with 20 px above, below, and to the left. 

illustration
120px x 80px, vertically centered with 20 px above, below, and to the right.

**Comment by ericsoco** [comment]
This design describes the default / "inactive" state for each behavior, but does not indicate "active" and "selected" states. Per our earlier conversation, each behavior can be:
- inactive (not active in the simulation, nor touched by visitor)
- active (active in the simulation, not (necessarily) touched by visitor)
- selected (touched by the visitor)

I'm open to other ways to handle this, but at the very least I think we should highlight the behaviors that are currently active in the simulation. If the callout at bottom is pointing at the selected behavior, that might be enough (not sure about when there are two or more behaviors stacked).

**Comment by ericsoco** [comment]
Also @nicolettehayes what do you think we should do about the fact that the text often does not fit in the bars? (This isn't even the gerund form, it's the shortest possible form of the verb...)

![screen shot 2017-02-27 at 11 03 50 pm](https://cloud.githubusercontent.com/assets/1127259/23395037/582be6b4-fd41-11e6-814d-ff4790772b5d.png)

**Comment by ericsoco** [comment]
Another question -- what do you think about a dark/light background gradient on this bar graph, to reinforce night/day? If you give me color+opacity for night and for day, I can handle the rest.

**Comment by ericsoco** [comment]
And another! I have to set the times of day based on the config. I'm already cheating a bit; dawn and dusk are configured to be 1 hour long, but they're actually ~1/2 hour in the real world. You specify two-hour long periods.

We end up with squished labels:
![screen shot 2017-02-27 at 11 32 20 pm](https://cloud.githubusercontent.com/assets/1127259/23395763/324364fa-fd45-11e6-98ae-8eef717142e7.png)

We can maybe go ahead and cheat and call dawn and dusk two hours to fit the labels, but that's 4x reality so I'm reluctant to do so...not sure. ?

**Comment by ericsoco** [comment]
Oy, final question sorry!

Prochlorococcus and SAR116 both have periods in which there are 3 behaviors happening simultaneously. As you can see above, that leaves us without enough room for the illustration below the timeline. Don't want to make the bars too small, because then they're less legible and less buttony/interactive-looking...thoughts?

**Comment by nicolettehayes** [comment]
My responses (you already know, but wanted to document):

1. inactive/active/selected is resolved by not having a "selected" state at all. 
when there are 2 simultaneous functions, they will have a shared label.
2. let's revisit fitting the words onto the bars once we have our revised list of functions implemented.
3. I am hesitant to bring in a dark/light background gradient...because I already tried. And failed.
4. I would love to cheat and call dawn/dusk 2 hours, also, we can simplify morning+afternoon=day
5. 2 rows will hopefully be the maximum number of rows when all is said and done.
