### ISSUE TITLE
No death during interesting behaviors

### ISSUE THREAD

**Issue by ericsoco** [stamen/living-liquid#34]
Can be jarring to have a bug doing something interesting, e.g. SAR116 swimming, and then all of a sudden die (disappear from view while drawing attention to itself). Think on ways to mitigate this.

**Comment by joycema** [comment]
My thoughts on times when death needs to hold off:
1 - do not allow infected proc to die... they will die soon enough and not sure if inside viruses also die.  Just to make it simple, just don't let the infected Proc die.
2 - do not allow death x time-units before momentary events.  
3 - don't worry about continuous states.  death can happen anytime during a continuous state.

**Comment by wonga00** [comment]
preventing death on infection with https://github.com/stamen/living-liquid/commit/5a78f0587d173e3d023bec607c06884fe6b1f5ad
