### ISSUE TITLE
SAR: bundle swimming + eating in function illustration

### ISSUE THREAD

**Issue by ericsoco** [stamen/living-liquid#46]
For now, at least (see #45), swimming and eating remain as two bars in the timeline. But, their function illustration below the timeline should be bundled into a single description + illustration that is shown for both.

**Comment by ericsoco** [comment]
Code handles this by just displaying a callout for the first behavior it finds for the current time. So, only thing left now is to update config (for "move" behavior) to display info about both swimming and eating.

**Comment by nicolettehayes** [comment]
Latest text from Kevin (includes a combined function illustration for swimming/eating)

[Metagenomics—all text—3.10.17.docx](https://github.com/stamen/living-liquid/files/846135/Metagenomics.all.text.3.10.17.docx)
