### ISSUE TITLE
Ensure app build/deploy is seamless

### ISSUE THREAD

**Issue by ericsoco** [stamen/living-liquid#53]
So that @sconnelley can pick it up and run with it, esp. without the table for testing.

**Comment by ericsoco** [comment]
Also make sure it's well documented.

**Comment by emilyhobson** [comment]
And TeamViewer orientation!

**Comment by ericsoco** [comment]
![screen-shot-2017-03-03-at-10 37 07-am](https://cloud.githubusercontent.com/assets/1127259/23564030/f3eeffbe-fffd-11e6-8f0c-7423113b4560.jpg)
