### ISSUE TITLE
Determine lifespan by organism type

### ISSUE THREAD

**Issue by ericsoco** [stamen/living-liquid#64]
This is on Jen + Elisha's plate. Once we have the answer, encode the values into `particles.json`.

**Comment by nicolettehayes** [comment]
In the spreadsheet! https://docs.google.com/spreadsheets/d/1N0DhkQ9osKbXjEREfkXH4eb6_dQ-3Kn76n8Wcj9Cc9o/edit#gid=926736479

**Comment by sconnelley** [comment]
@nicolettehayes -- just so I am clear and I am reading the spreadsheet correctly:
* Prochlorococcus can live for 1 to 2 days
* SAR116 can live for 2 -3 days
* Virus can live for 2 - 3 days

**Comment by joycema** [comment]
This is not important for basic functionality and comprehension.

**Comment by sconnelley** [comment]
I am little unclear then about this issue, is it needed? What is expected resolution?

**Comment by joycema** [comment]
Pls skip this issue --- I've put it on lowest priority --- 9 (Explo priority rating)

**Comment by joycema** [comment]
changed in config files for each microbe.
